dist: trusty
sudo: false
os: linux
language: node_js
node_js:
  - "10"
cache: npm
install:
  - "cd music/"
  - "npm install"
stages:
  - NPM BUILD
  - DEPLOY PROD

jobs:
  include:
    - stage: NPM BUILD
      script:
        - "npm run build"
    - stage: DEPLOY PROD
      script:
        - "cd build && find . -type f -exec curl --ftp-create-dirs -T {} ${SFTP_URL}{} --user ${SFTP_USER}:${SFTP_PASSWORD} \;"
