---
cache: npm
dist: trusty
install:
  - "cd music/"
  - "npm install"
jobs:
  include:
    - script:
        - "npm run build"
      stage: "NPM BUILD"
    - script:
        - "cd build && find . -type f -exec curl --ftp-create-dirs -T {} ${SFTP_URL}{} --user ${SFTP_USER}:${SFTP_PASSWORD ;"
      stage: "DEPLOY PROD"
language: node_js
node_js:
  - "10"
os: linux
stages:
  - "NPM BUILD"
  - "DEPLOY PROD"
sudo: false
