language: node_js
node_js:
  - "10"
cache: npm
# branches:
#  only:
#    - master
install:
  - "cd music/"
  - "npm install"
stages:
  - NPM BUILD

jobs:
  include:
    - stage: NPM BUILD
      script:
        - "npm run build"

after_success:
  - test $TRAVIS_BRANCH = "feature/show-last-update" &&
    cd build &&
    find . -type f -exec curl --ftp-create-dirs -T {} ${SFTP_URL}{} --user ${SFTP_USER}:${SFTP_PASSWORD} \;
