language: node_js
node_js:
  - "10"
cache: npm
branches:
  only:
    - master
install:
  - "cd music/"
  - "npm install"
stages:
  - NPM TEST
  - NPM BUILD

jobs:
  include:
    - stage: NPM TEST
      script:
        - "npm run test"

    - stage: NPM BUILD
      script:
        - "npm run build
