on:
  push:
    branches:
      - feature/auto-version-bump
jobs:
  update-version:
    name: Update Version
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        uses: codacy/git-version@2.2.0


  deploy:
      name: Deploy Frontend and API to Production
      runs-on: ubuntu-latest
      needs: build
      if: github.ref == 'refs/heads/master'
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2

        - name: Download production artifact
          uses: actions/download-artifact@v2
          with:
            name: frontend
            path: music/build

        - name: Replace Spotify Client ID
          uses: jwsi/secret-parser@v1
          with:
            # File where GitHub Actions Secrets references should be parsed and replaced
            filename: music-api/api.php
            # Name of secret to search for in the designated file
            secret-name: "SPOTIFY_CLIENT_ID"
            # Value of secret to replace reference with in designated file
            secret-value: ${{ secrets.SPOTIFY_CLIENT_ID  }}

        - name: Replace Spotify Client Secret
          uses: jwsi/secret-parser@v1
          with:
            # File where GitHub Actions Secrets references should be parsed and replaced
            filename: music-api/api.php
            # Name of secret to search for in the designated file
            secret-name: "SPOTIFY_CLIENT_SECRET"
            # Value of secret to replace reference with in designated file
            secret-value: ${{ secrets.SPOTIFY_CLIENT_SECRET  }}

        - name: FTP Deployment Frontend
          uses: airvzxf/ftp-deployment-action@latest
          with:
            server: ${{ secrets.FTP_URL }}
            user: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            local_dir: music/build/
            delete: true

        - name: FTP Deployment API
          uses: airvzxf/ftp-deployment-action@latest
          with:
            server: ${{ secrets.FTP_URL }}
            user: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            local_dir: music-api/
            delete: false
