# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI



on:
  push:
    branches: [ master, feature/travis-ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: music

      - run: npm run build --if-present
        working-directory: music

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          # ftp server
          server: ${{ secrets.FTP_URL }}
          # ftp username
          username: ${{ secrets.FTP_USERNAME }}
          # ftp password
          password: ${{ secrets.FTP_PASSWORD }}
          # Folder to upload from, must end with trailing slash /
          local-dir: music/build/
